services:
    # Change the container name
    postgres:
        image: postgres:latest
        container_name: my_postgres_db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: my_database
            POSTGRES_USER: my_user
            POSTGRES_PASSWORD: my_password
        volumes:
            - ./data:/var/lib/artgallery/postgresql/data
